language: python
python:
- 2.7
install:
- echo "nothing to do"
script:
- echo "nothing to do"
- 
deploy:
  provider: pypi
  server: https://test.pypi.org/legacy/
  user: testing.gabriele.giammatteo
  password:
    secure: GcEUduLllOOgKTZSTPqHzqaDv6ak4vW2CT8qJ/UOtqkgbfcrVBSOGcBXI/Y3WsBufQ252zRjNa08hFooKA9b5TLVlxKfrMCAMkEYE3MHp/65BFpTSPXlo3rwJzbhJUCNKC5WMsXMXn/mr+Myl17vGyM98CbDKTY0xerDWeE/M/Ttd2vno6fLQf6YW2VfIi0zZSZwsUC/subVpYqt4ZYW/kITcwryb3tNSRTxwnDelEERXjZpzcKylH1O2Z9Hk66HX4fywjLwtS5nCAe4XYe3wrgVhZFxYE0dpoeyqP8QDziIshNgrJtddiWT2T8ad7QtDKImyCZHqNb7zEZl96isZ+ml+82hGdWgV368w9f1So3NQCVSFlgtTCk/IXjZnZekm/5v6i5QKFhh+2V4OZNoDXT5STDmRh1JUrJLKXijm0Wg6r+Sf58My+od7eXtpEA6jZKgNFog8PfcFHoq8N3aCFqigFlMqvJqWNVQhlkzxqc+bK2OrL+MdThmGJmkXRLZ51+638vzYixsLhbG7bO1FZlNaDLIXZLw5qEjQmqLMHfOmj3ykOGtbR1MqAy6I/VatAW6oPGm6NHeG1+7NW7nvLB71ZJjqG/aas6EZZeagT76BwXcUUqJaSBBC98/oxNqZAKdb8TzKTw2VhAPlgWMN6P4ALp/qoMdLTx3LzGQmKQ=
  distributions: sdist bdist_wheel
  skip_existing: true
  skip_cleanup: true
