language: python
python:
- 2.7
install:
- echo "nothing to do"
script:
- echo "nothing to do"
- 
deploy:
  provider: pypi
  server: https://test.pypi.org/legacy/
  user: testing.gabriele.giammatteo
  password:
    secure: T1ISjTJYedUw+NW3WXmgzehFH6TzEJrhuWnDqGDbbLz9TUo9phK+SGO74+O32KonGKqdv8JXttrGFZoY4N2W5QUVKWL7lDUoQaUsjFnKEN4qtSsWN7jcocKEEJzSrxAtG8m7btKKXowBxEGn2980OtBTVz+Ts/5RzPrtGRavoVj3VRjhuhn8wu1gKdw8/fe8ipb3LSveeSQMsU5IOsw2xG+NzebTmx3XS/RHcQSmsUnTeTIzgW+dUnUr7TJ5RamICOiUav73S7LBUH7P4pqdu2eFCBFGM8nc0lKB0ET9tKXS01FP9PXCKEG7duWizkEoYKhPp6+41GJyY29fQQQiNT87VzRqnQPS56tEUOns9uxzU9l4r+/lEf532qMJltXkxgXlUMIsMi42vxkJYa1XziehEzZ7gJCckNeko7dDWiwwOmYVhdp1HwWbmlDUmh3XoHzjdilWwI2fnBzqbHQohgpEin1A8HW47e8ZLUPb1FcpFTIolatzwYT992UkRrPUoVPF76a0kkIfREmNvq/QXYt1AXu/25FgHhZscGSm441DdWJCIuWjnmFy2SU0CGvuiZYRTmKWD9JCxOW3zWGNpJUPSyf+UVJBG6s/iFhtk/LhJ3eAF2blrpIlapMunfHZ1knLu5GGr4IA9UspcKIBotwugSCv4NfFMayojHFhhQM=
  distributions: sdist bdist_wheel
  skip_existing: true
  skip_cleanup: true
